name: "JS Automations"
version: "2.30.0"
slug: "js_automations"
description: "JavaScript Automations-Engine"
arch:
  - aarch64
  - amd64
  - armv7
startup: "services"
boot: "auto"
ingress: true
ingress_port: 3000
panel_icon: "mdi:nodejs"
homeassistant_api: true
hassio_role: manager
map:
  - config:rw
options:
  ui_language: "de"
schema:
  ui_language: list(de|en)