/// <reference path="./entities.d.ts" />
/// <reference path="./services.d.ts" />
/**
 * AUTO-GENERATED BY JS AUTOMATIONS - DO NOT EDIT
 * This file provides the core TypeScript definitions for the `ha` global object.
 * Dynamic parts (EntityID, GlobalStoreSchema, ServiceMap) are merged at runtime.
 */

// Placeholder for dynamically generated entities.d.ts content
// This will be replaced by the actual content of entities.d.ts
interface HAEntities { }

// Placeholder for dynamically generated store.d.ts content
// This will be replaced by the actual content of store.d.ts
interface GlobalStoreSchema /*__JSA_STORE_SCHEMA__*/ {}

/**
 * ServiceMap Interface.
 * This interface is extended by the automatically generated services.d.ts.
 * If you see no autocomplete, ensure the Add-on has connected to HA at least once.
 */
interface ServiceMap { }

/** Helper to generate all possible 'domain.service' strings from ServiceMap */
type AllServiceIds = {
    [D in keyof ServiceMap & string]: D extends string 
        ? { [S in keyof ServiceMap[D] & string]: S extends string ? `${D}.${S}` : never }[keyof ServiceMap[D] & string]
        : never
}[keyof ServiceMap & string];

/** Helper to extract the data payload type for a combined service ID */
type ServiceData<T extends string> = T extends `${infer D}.${infer S}`
    ? D extends keyof ServiceMap
        ? S extends keyof ServiceMap[D] 
            ? { 
                [K in keyof ServiceMap[D][S]]: K extends 'entity_id' 
                    ? EntityID | EntityID[] 
                    : ServiceMap[D][S][K] 
              }
            : Record<string, any>
        : Record<string, any>
    : Record<string, any>;

/** Helper to map a domain to its available services as methods */
type EntityServices<T extends string> = T extends `${infer Domain}.${infer Rest}`
    ? Domain extends keyof ServiceMap 
        ? { [S in keyof ServiceMap[Domain] & string]: (data?: Partial<ServiceMap[Domain][S]>) => Promise<EntityServices<T>> } & EntityMethods<T>
        : Record<string, (data?: any) => Promise<any>> & EntityMethods<T>
    : Record<string, (data?: any) => Promise<any>> & EntityMethods<T>;

/** Helper to extract only literal keys (excluding index signatures) for better IntelliSense */
type KnownKeys<T> = keyof { [K in keyof T as string extends K ? never : number extends K ? never : K]: any };

/** Helper to extract attribute keys for a specific entity ID with autocomplete fallback */
type AttributeKey<T extends string> = T extends keyof HAEntities 
    ? (HAEntities[T] extends HAState<infer A> ? (KnownKeys<A> | (string & {})) : (KnownKeys<HAAttributes> | (string & {})))
    : (KnownKeys<HAAttributes> | (string & {}));

interface EntityMethods<T extends string> {
    /** Pauses the execution chain for a specific duration. */
    wait(ms: number): Promise<EntityServices<T>>;
    /** Gets a specific attribute value for this entity. */
    getAttribute<K extends AttributeKey<T>>(name: K): T extends keyof HAEntities 
        ? (HAEntities[T] extends HAState<infer A> ? (K extends keyof A ? A[K] : any) : any) 
        : any;
    /** The current state value of the entity. */
    readonly state: string | undefined;
    /** The attributes of the entity, automatically typed if the entity ID is known. */
    readonly attributes: T extends keyof HAEntities ? (HAEntities[T] extends HAState<infer A> ? A : HAAttributes) : HAAttributes;
}

/** Helper to map a domain to its available services as batch methods */
type SelectorServices<T extends string> = T extends `${infer Domain}.${infer Rest}`
    ? Domain extends keyof ServiceMap 
        ? { [S in keyof ServiceMap[Domain] & string]: (data?: Partial<ServiceMap[Domain][S]>) => Promise<EntitySelector & SelectorServices<T>> } & { throttle(ms: number): EntitySelector & SelectorServices<T>; wait(ms: number): Promise<EntitySelector & SelectorServices<T>> }
        : Record<string, (data?: any) => Promise<EntitySelector>> & { throttle(ms: number): EntitySelector; wait(ms: number): Promise<EntitySelector> }
    : Record<string, (data?: any) => Promise<EntitySelector>> & { throttle(ms: number): EntitySelector; wait(ms: number): Promise<EntitySelector> };

/** Type that provides autocomplete for known keys in GlobalStoreSchema while allowing any string. */
type StoreKey = keyof GlobalStoreSchema | (string & { _?: never });

/** Type alias for known Home Assistant entity IDs with fallback to any string */
type EntityID = keyof HAEntities | (string & { _?: never });

/**
 * Represents a Home Assistant entity state.
 */
interface HAState<T = HAAttributes> {
    entity_id: string;
    state: string;
    attributes: T;
    last_changed: string;
    last_updated: string;
    context: {
        id: string;
        parent_id: string | null;
        user_id: string | null;
    };
}

/**
 * Represents common Home Assistant entity attributes.
 */
interface HAAttributes {
    friendly_name?: string;
    icon?: string;
    device_class?: string;
    unit_of_measurement?: string;
    [key: string]: any;
}

/** Specific attributes for light entities */
interface LightAttributes extends HAAttributes {
    brightness?: number;
    color_temp?: number;
    rgb_color?: [number, number, number];
    xy_color?: [number, number];
    hs_color?: [number, number];
    effect?: string;
    effect_list?: string[];
    supported_color_modes?: string[];
    color_mode?: string;
}

/** Specific attributes for media player entities */
interface MediaPlayerAttributes extends HAAttributes {
    volume_level?: number;
    is_volume_muted?: boolean;
    media_content_id?: string;
    media_content_type?: string;
    media_duration?: number;
    media_position?: number;
    media_title?: string;
    media_artist?: string;
    media_album_name?: string;
    source?: string;
    source_list?: string[];
}

/** Specific attributes for climate entities */
interface ClimateAttributes extends HAAttributes {
    current_temperature?: number;
    temperature?: number;
    target_temp_high?: number;
    target_temp_low?: number;
    fan_mode?: string;
    fan_modes?: string[];
    hvac_action?: string;
    hvac_modes?: string[];
    preset_mode?: string;
    preset_modes?: string[];
}

/** Specific attributes for sensor entities */
interface SensorAttributes extends HAAttributes {
    state_class?: 'measurement' | 'total' | 'total_increasing';
    last_reset?: string;
}

/**
 * Represents a change event for an entity state.
 */
interface StateChangeData {
    entity_id: EntityID;
    state: string;
    old_state: string | null;
    attributes: Record<string, any>;
}

/**
 * Represents an error that occurred in the background (e.g., unhandled promise rejection).
 */
interface BackgroundErrorData {
    message: string;
    stack: string;
    type: 'background' | 'script';
}

/**
 * Defines the global `ha` object available in JS Automations scripts.
 * Provides access to Home Assistant functionalities, logging, and global store.
 */
declare const ha: HA;
declare const schedule: (cronExpression: string, callback: () => void | Promise<void>) => any;
declare const sleep: (ms: number) => Promise<void>;

interface HA {
    /**
     * Returns a localized string based on the current language.
     * @param mapping Object mapping language codes to strings (e.g. { en: "Hi", de: "Hallo" })
     * @param fallback Optional fallback string if language is not found
     */
    localize(mapping: Record<string, string>, fallback?: string): string;

    /** The current language of the Home Assistant instance. */
    readonly language: string;

    // --- Logging ---
    /** Logs a debug message to the console. */
    debug(message: any): void;
    /** Logs an informational message to the console. */
    log(message: any): void;
    /** Logs a warning message to the console. */
    warn(message: any): void;
    /** Logs an error message to the console. */
    error(message: any): void;

    // --- Script Lifecycle ---
    /** Stops the current script. */
    stop(reason?: string): void;
    /** Restarts the current script. */
    restart(reason?: string): void;
    /** Registers a callback to be executed when the script is stopped. */
    onStop(callback: () => void | Promise<void>): void;
    /** Registers a callback to be executed when an unhandled error occurs. */
    onError(callback: (error: BackgroundErrorData) => void): void;

    // --- Home Assistant Services & Entities ---
    /** 
     * Returns a fluent API for a specific entity with domain-specific services.
     * @param entityId The entity ID (e.g., 'light.living_room').
     */
    entity<K extends EntityID>(entityId: K): EntityServices<K & string>;

    /** 
     * @deprecated Use ha.call() instead for a cleaner 'domain.service' syntax.
     * Calls a Home Assistant service. 
     */
    callService<D extends keyof ServiceMap | (string & {}), S extends (D extends keyof ServiceMap ? keyof ServiceMap[D] : string)>(
        domain: D,
        service: S,
        data?: D extends keyof ServiceMap ? (S extends keyof ServiceMap[D] ? ServiceMap[D][S] : any) : any
    ): void;

    /**
     * Safely calls a Home Assistant service using the 'domain.service' format.
     * Automatically catches and logs errors in the master process to prevent script crashes.
     * @param serviceId The service to call (e.g., 'light.turn_on' or 'tts.cloud_say').
     * @param data Optional service data payload.
     */
    call<T extends AllServiceIds | (string & {})>(
        serviceId: T,
        data?: T extends AllServiceIds ? ServiceData<T> : Record<string, any>
    ): void;

    /**
     * Updates the state and/or attributes of an existing Home Assistant entity.
     * If the entity was registered via `ha.register`, it will use the native integration.
     * Otherwise, it falls back to the legacy HTTP API.
     * @param entityId The entity ID to update (e.g., 'sensor.my_sensor').
     * @param state The new state value.
     * @param attributes Optional attributes to set.
     */
    update(entityId: EntityID, state: string | number | boolean | null, attributes?: Record<string, any>): void;
    /**
     * Updates only the attributes of an existing Home Assistant entity, preserving its current state.
     * @param entityId The entity ID to update (e.g., 'sensor.my_sensor').
     * @param attributes Attributes to set or update.
     */
    update(entityId: EntityID, attributes: Record<string, any>): void;

    /**
     * @deprecated Use ha.update() instead.
     * Updates the state and/or attributes of an existing Home Assistant entity.
     * @param entityId The entity ID to update.
     * @param state The new state value.
     * @param attributes Optional attributes to set.
     */
    updateState(entityId: EntityID, state: string | number | boolean | null, attributes?: Record<string, any>): void;

    /**
     * Registers a native Home Assistant entity via the JS Automations integration.
     * This creates a persistent entity in Home Assistant's registry.
     * @param entityId The desired entity ID (e.g., 'sensor.my_value').
     * @param config Configuration for the entity (name, icon, unit_of_measurement, device_class, etc.).
     */
    register(entityId: string, config?: Record<string, any>): void;

    /** A live cache of all Home Assistant entity states. */
    readonly states: HAEntities;
    /** Gets the current state object for a given entity ID. */
    getState<K extends EntityID>(entityId: K): K extends keyof HAEntities ? HAEntities[K] : HAState | undefined;
    /** Gets a specific attribute value for an entity. */
    getAttr<K extends EntityID>(entityId: K, attribute: AttributeKey<K>): any;
    /** Gets the state value of an entity, converting 'on'/'off' to boolean and numbers to number. */
    getStateValue(entityId: EntityID): string | number | boolean | undefined;
    /** Gets the members of a group entity. */
    getGroupMembers(entityId: EntityID): EntityID[];

    /**
     * Reads a value from the script's header (e.g., `@name`, `@icon`).
     * @param key The header key (e.g., 'name', 'icon').
     * @param defaultValue A fallback value if the header is not found.
     */
    getHeader(key: string, defaultValue?: any): any;

    /**
     * Selects one or more entities based on a pattern for bulk actions.
     * @param pattern An entity ID, a wildcard pattern (e.g., 'light.*'), an array of entity IDs, or a RegExp.
     */
    select<P extends string>(pattern: P | EntityID[] | RegExp): EntitySelector & SelectorServices<P>;

    /**
     * Registers a callback to be executed when an entity's state changes.
     * @param pattern An entity ID, a wildcard pattern (e.g., 'light.*'), an array of entity IDs, or a RegExp.
     * @param callback The function to call when the state changes.
     */
    on(pattern: EntityID | EntityID[] | RegExp | string, callback: (event: StateChangeData) => void): void;
    /**
     * Registers a callback to be executed when an entity's state changes, with an optional filter.
     * @param pattern An entity ID, a wildcard pattern (e.g., 'light.*'), an array of entity IDs, or a RegExp.
     * @param filter A filter string ('ne', 'eq', 'gt', 'ge', 'lt', 'le') or a specific value to compare against.
     * @param callback The function to call when the state changes and the filter condition is met.
     */
    on(pattern: EntityID | EntityID[] | RegExp | string, filter: ChangeFilter | string | number, callback: (event: StateChangeData) => void): void;
    /**
     * Registers a callback to be executed when an entity's state changes, with a filter and an optional threshold.
     * @param pattern An entity ID, a wildcard pattern (e.g., 'light.*'), an array of entity IDs, or a RegExp.
     * @param filter A filter string ('ne', 'eq', 'gt', 'ge', 'lt', 'le').
     * @param threshold A numeric or string threshold to compare the new state against.
     * @param callback The function to call when the state changes and the filter condition is met.
     */
    on(pattern: EntityID | EntityID[] | RegExp | string, filter: ChangeFilter, threshold: string | number, callback: (event: StateChangeData) => void): void;

    /**
     * Waits for a specific event or state change.
     * Returns a Promise that resolves when the condition is met.
     * @param pattern An entity ID, a wildcard pattern (e.g., 'light.*'), an array of entity IDs, or a RegExp.
     * @param options Optional: { timeout?: number }
     */
    waitFor(pattern: EntityID | EntityID[] | RegExp | string, options?: { timeout?: number }): Promise<StateChangeData>;
    /**
     * Waits for a specific event or state change with a filter.
     * @param pattern An entity ID, a wildcard pattern (e.g., 'light.*'), an array of entity IDs, or a RegExp.
     * @param filter A filter string ('ne', 'eq', 'gt', 'ge', 'lt', 'le') or a specific value to compare against.
     * @param options Optional: { timeout?: number }
     */
    waitFor(pattern: EntityID | EntityID[] | RegExp | string, filter: ChangeFilter | string | number, options?: { timeout?: number }): Promise<StateChangeData>;
    /**
     * Waits for a specific event or state change with a filter and threshold.
     * @param pattern An entity ID, a wildcard pattern (e.g., 'light.*'), an array of entity IDs, or a RegExp.
     * @param filter A filter string ('ne', 'eq', 'gt', 'ge', 'lt', 'le').
     * @param threshold A numeric or string threshold to compare the new state against.
     * @param options Optional: { timeout?: number }
     */
    waitFor(pattern: EntityID | EntityID[] | RegExp | string, filter: ChangeFilter, threshold: string | number, options?: { timeout?: number }): Promise<StateChangeData>;

    /**
     * Waits until a specific condition function returns true.
     * This is useful for complex state checks involving multiple entities.
     * @param condition A function that returns true when the desired state is met.
     * @param options Optional: { timeout?: number, pollInterval?: number }
     */
    waitUntil(condition: () => boolean, options?: { timeout?: number, pollInterval?: number }): Promise<void>;

    /**
     * Provides access to the global persistent store.
     */
    store: {
        /**
         * A direct reference to the current values in the store.
         * Accessing properties directly on `ha.store.val` will not trigger change listeners or persistence.
         * Use `ha.store.get` and `ha.store.set` for reactive and persistent operations.
         */
        readonly val: GlobalStoreSchema;

        /**
         * Sets a value in the Global Store.
         * @param key The key to store the value under.
         * @param value The value to store.
         * @param isSecret If true, the value will be masked in the UI.
         */
        set<K extends keyof GlobalStoreSchema>(key: K, value: GlobalStoreSchema[K], isSecret?: boolean): void;
        set<T = any>(key: string & { _?: never }, value: T, isSecret?: boolean): void;

        /**
         * Retrieves a value from the Global Store.
         * @param key The key of the value to retrieve.
         * @returns The stored value, or `undefined` if not found.
         */
        get<K extends keyof GlobalStoreSchema>(key: K): GlobalStoreSchema[K];
        get<T = any>(key: string & { _?: never }): T | undefined;

        /**
         * Deletes a value from the Global Store.
         * @param key The key of the value to delete.
         */
        delete(key: StoreKey): void;

        /**
         * Registers a callback to be executed when a specific store key's value changes.
         * @param key The store key to listen for changes on.
         * @param callback The function to call when the value changes.
         */
        on<K extends keyof GlobalStoreSchema>(key: K, callback: (newValue: GlobalStoreSchema[K] | undefined, oldValue: GlobalStoreSchema[K] | undefined) => void): void;
        on<T = any>(key: string & { _?: never }, callback: (newValue: T | undefined, oldValue: T | undefined) => void): void;
    };

    /**
     * Creates a deep proxy for an object stored in `ha.store`,
     * automatically saving changes back to the store when properties are modified.
     * Ideal for managing complex configuration objects persistently.
     * @param key The store key where the object is saved.
     * @param defaultValue An optional default value if the key is not found in the store.
     * @returns A Proxy object that automatically persists changes.
     */
    persistent<K extends keyof GlobalStoreSchema>(key: K, defaultValue?: GlobalStoreSchema[K]): GlobalStoreSchema[K];
    persistent<T = any>(key: string & { _?: never }, defaultValue?: T): T;
}

/**
 * Represents a selection of Home Assistant entities for bulk operations.
 */
declare class EntitySelector {
    readonly list: HAState[];
    readonly count: number;

    constructor(entities: HAState[], ha: HA);

    /** Filters the current selection using a callback function. */
    where(callback: (entity: HAState) => boolean): EntitySelector;
    /** Executes a function for each entity in the selection. */
    each(callback: (entity: HAState) => void): EntitySelector;
    /** Calls a service for all entities in the selection. */
    call(service: string, data?: Record<string, any>): Promise<this>;
    /** Sets a delay in milliseconds between each entity call in a batch action. */
    throttle(ms: number): this;
    /** Waits for the specified amount of time. Useful for chaining actions. */
    wait(ms: number): Promise<this>;
    /** Expands groups to their members. */
    expand(): EntitySelector;
    /** Returns the raw array of state objects. */
    toArray(): HAState[];
}

/**
 * Defines the possible filter types for `ha.on` and `ha.waitFor`.
 */
type ChangeFilter = 'ne' | 'eq' | 'gt' | 'ge' | 'lt' | 'le';