/// <reference path="./entities.d.ts" />
/// <reference path="./services.d.ts" />
/**
 * AUTO-GENERATED BY JS AUTOMATIONS - DO NOT EDIT
 * This file provides the core TypeScript definitions for the `ha` global object.
 * Dynamic parts (EntityID, GlobalStoreSchema, ServiceMap) are merged at runtime.
 */

// Placeholder for dynamically generated entities.d.ts content
// This will be replaced by the actual content of entities.d.ts
interface HAEntities { }

// Placeholder for dynamically generated store.d.ts content
// This will be replaced by the actual content of store.d.ts
interface GlobalStoreSchema /*__JSA_STORE_SCHEMA__*/ {}

/**
 * ServiceMap Interface.
 * This interface is extended by the automatically generated services.d.ts.
 * If you see no autocomplete, ensure the Add-on has connected to HA at least once.
 */
interface ServiceMap { }

/** Helper to generate all possible 'domain.service' strings from ServiceMap */
type AllServiceIds = {
    [D in keyof ServiceMap & string]: D extends string 
        ? { [S in keyof ServiceMap[D] & string]: S extends string ? `${D}.${S}` : never }[keyof ServiceMap[D] & string]
        : never
}[keyof ServiceMap & string];

/** Helper to extract the data payload type for a combined service ID */
type ServiceData<T extends string> = T extends `${infer D}.${infer S}`
    ? D extends keyof ServiceMap
        ? S extends keyof ServiceMap[D] 
            ? { 
                [K in keyof ServiceMap[D][S]]: K extends 'entity_id' 
                    ? EntityID | EntityID[] 
                    : ServiceMap[D][S][K] 
              } & { entity_id?: EntityID | EntityID[] }
            : Record<string, any>
        : Record<string, any>
    : Record<string, any>;

/** Helper to map a domain to its available services as methods */
type EntityServices<T extends string> = T extends `${infer Domain}.${infer Rest}`
    ? Domain extends keyof ServiceMap 
        ? { [S in keyof ServiceMap[Domain] & string]: (data?: Partial<ServiceMap[Domain][S]>) => Promise<EntityServices<T>> } & EntityMethods<T>
        : Record<string, (data?: any) => Promise<any>> & EntityMethods<T>
    : Record<string, (data?: any) => Promise<any>> & EntityMethods<T>;

/** Helper to extract only literal keys (excluding index signatures) for better IntelliSense */
type KnownKeys<T> = keyof { [K in keyof T as string extends K ? never : number extends K ? never : K]: any };

/** Helper to extract attribute keys for a specific entity ID with autocomplete fallback */
type AttributeKey<T extends string> = T extends keyof HAEntities 
    ? (HAEntities[T] extends HAState<infer A> ? (KnownKeys<A> | (string & {})) : (KnownKeys<HAAttributes> | (string & {})))
    : (KnownKeys<HAAttributes> | (string & {}));

interface EntityMethods<T extends string> {
    /** Pauses the execution chain for a specific duration. */
    wait(ms: number): Promise<EntityServices<T>>;
    /** Gets a specific attribute value for this entity. */
    getAttribute<K extends AttributeKey<T>>(name: K): T extends keyof HAEntities 
        ? (HAEntities[T] extends HAState<infer A> ? (K extends keyof A ? A[K] : any) : any) 
        : any;
    /** The current state value of the entity. */
    readonly state: string | undefined;
    /** The attributes of the entity, automatically typed if the entity ID is known. */
    readonly attributes: T extends keyof HAEntities ? (HAEntities[T] extends HAState<infer A> ? A : HAAttributes) : HAAttributes;
}

/** Helper to map a domain to its available services as batch methods */
type SelectorServices<T extends string> = T extends `${infer Domain}.${infer Rest}`
    ? Domain extends keyof ServiceMap 
        ? { [S in keyof ServiceMap[Domain] & string]: (data?: Partial<ServiceMap[Domain][S]>) => Promise<EntitySelector & SelectorServices<T>> } & { throttle(ms: number): EntitySelector & SelectorServices<T>; wait(ms: number): Promise<EntitySelector & SelectorServices<T>> }
        : Record<string, (data?: any) => Promise<EntitySelector>> & { throttle(ms: number): EntitySelector; wait(ms: number): Promise<EntitySelector> }
    : Record<string, (data?: any) => Promise<EntitySelector>> & { throttle(ms: number): EntitySelector; wait(ms: number): Promise<EntitySelector> };

/** Type that provides autocomplete for known keys in GlobalStoreSchema while allowing any string. */
type StoreKey = keyof GlobalStoreSchema | (string & { _?: never });

/** Type alias for known Home Assistant entity IDs with fallback to any string */
type EntityID = keyof HAEntities | (string & { _?: never });

/**
 * Represents a Home Assistant entity state.
 */
interface HAState<T = HAAttributes> {
    entity_id: string;
    state: string;
    attributes: T;
    last_changed: string;
    last_updated: string;
    context: {
        id: string;
        parent_id: string | null;
        user_id: string | null;
    };
}

/**
 * Represents common Home Assistant entity attributes.
 */
interface HAAttributes {
    friendly_name?: string;
    icon?: string;
    device_class?: string;
    unit_of_measurement?: string;
    [key: string]: any;
}

/** Specific attributes for light entities */
interface LightAttributes extends HAAttributes {
    brightness?: number;
    color_temp?: number;
    rgb_color?: [number, number, number];
    xy_color?: [number, number];
    hs_color?: [number, number];
    effect?: string;
    effect_list?: string[];
    supported_color_modes?: string[];
    color_mode?: string;
}

/** Specific attributes for media player entities */
interface MediaPlayerAttributes extends HAAttributes {
    volume_level?: number;
    is_volume_muted?: boolean;
    media_content_id?: string;
    media_content_type?: string;
    media_duration?: number;
    media_position?: number;
    media_title?: string;
    media_artist?: string;
    media_album_name?: string;
    source?: string;
    source_list?: string[];
}

/** Specific attributes for climate entities */
interface ClimateAttributes extends HAAttributes {
    current_temperature?: number;
    temperature?: number;
    target_temp_high?: number;
    target_temp_low?: number;
    fan_mode?: string;
    fan_modes?: string[];
    hvac_action?: string;
    hvac_modes?: string[];
    preset_mode?: string;
    preset_modes?: string[];
}

/** Specific attributes for sensor entities */
interface SensorAttributes extends HAAttributes {
    state_class?: 'measurement' | 'total' | 'total_increasing';
    last_reset?: string;
}

/**
 * Represents a change event for an entity state.
 */
interface StateChangeData {
    entity_id: EntityID;
    state: string;
    old_state: string | null;
    attributes: Record<string, any>;
}

/**
 * Represents an error that occurred in the background (e.g., unhandled promise rejection).
 */
interface BackgroundErrorData {
    message: string;
    stack: string;
    type: 'background' | 'script';
}

/**
 * Defines the global `ha` object available in JS Automations scripts.
 * Provides access to Home Assistant functionalities, logging, and global store.
 */
declare const ha: HA;
declare const schedule: (cronExpression: string, callback: () => void | Promise<void>) => any;
declare const sleep: (ms: number) => Promise<void>;

interface HA {
    /**
     * Returns a localized string based on the current language.
     * @param mapping Object mapping language codes to strings (e.g. { en: "Hi", de: "Hallo" })
     * @param fallback Optional fallback string if language is not found
     */
    localize(mapping: Record<string, string>, fallback?: string): string;

    /** The current language of the Home Assistant instance. */
    readonly language: string;

    // --- Logging ---
    /** Logs a debug message to the console. */
    debug(message: any): void;
    /** Logs an informational message to the console. */
    log(message: any): void;
    /** Logs a warning message to the console. */
    warn(message: any): void;
    /** Logs an error message to the console. */
    error(message: any): void;

    // --- Script Lifecycle ---
    /** Stops the current script. */
    stop(reason?: string): void;
    /** Restarts the current script. */
    restart(reason?: string): void;
    /** Registers a callback to be executed when the script is stopped. */
    onStop(callback: () => void | Promise<void>): void;
    /** Registers a callback to be executed when an unhandled error occurs. */
    onError(callback: (error: BackgroundErrorData) => void): void;

    // --- Home Assistant Services & Entities ---
    /** 
     * Returns a fluent API for a specific entity with domain-specific services.
     * @param entityId The entity ID (e.g., 'light.living_room').
     */
    entity<K extends EntityID>(entityId: K): EntityServices<K & string>;

    /** 
     * @deprecated Use ha.call() instead for a cleaner 'domain.service' syntax.
     * Calls a Home Assistant service. 
     */
    callService<D extends keyof ServiceMap | (string & {}), S extends (D extends keyof ServiceMap ? keyof ServiceMap[D] : string)>(
        domain: D,
        service: S,
        data?: D extends keyof ServiceMap ? (S extends keyof ServiceMap[D] ? ServiceMap[D][S] : any) : any
    ): void;

    /**
     * Safely calls a Home Assistant service using the 'domain.service' format.
     * Automatically catches and logs errors in the master process to prevent script crashes.
     * @param serviceId The service to call (e.g., 'light.turn_on' or 'tts.cloud_say').
     * @param data Optional service data payload.
     */
    call<T extends AllServiceIds | (string & {})>(
        serviceId: T,
        data?: T extends AllServiceIds ? ServiceData<T> : Record<string, any>
    ): void;

    /**
     * Sends an actionable notification and waits for the user's response.
     * Returns a Promise that resolves with the chosen action string,
     * or with `defaultAction` (default: `null`) if the timeout expires.
     *
     * Requires the HA companion app installed on at least one device.
     * 
     * **Note:** This does not work in the web browser as it relies on mobile app events.
     *
     * @example
     * const answer = await ha.ask("Garage door left open. Close it?", {
     *   title: "Garage",
     *   target: "notify.mobile_app_my_phone",
     *   defaultAction: "SNOOZE",
     *   actions: [
     *     { action: "CLOSE",  title: "Close now" },
     *     { action: "SNOOZE", title: "Remind in 30 min" },
     *     { action: "IGNORE", title: "Ignore" },
     *   ]
     * });
     * if (answer === "CLOSE") ha.entity('cover.garage').close_cover();
     * if (answer === "SNOOZE" || answer === null) setTimeout(checkGarage, 30 * 60 * 1000);
     */
    ask(message: string, options?: {
        /** Notification title shown in the push notification header. */
        title?: string;
        /**
         * Target notify service (e.g. `'notify.mobile_app_my_phone'` or just `'mobile_app_my_phone'`).
         * Defaults to `'notify.notify'` which broadcasts to all configured notifiers.
         */
        target?: string;
        /** Timeout in milliseconds before the promise resolves with `defaultAction`. Default: 60000 (1 min). */
        timeout?: number;
        /** Value resolved when the timeout expires. Default: `null`. */
        defaultAction?: string | null;
        /** Action buttons shown in the notification. Each `action` string is returned when tapped. */
        actions?: Array<{ action: string; title: string }>;
    }): Promise<string | null>;

    /**
     * Sends a notification via Home Assistant's notify service.
     * Defaults to `notify.notify` (broadcasts to all configured notifiers).
     *
     * **Note:** Advanced data features (images, actions) are only supported by mobile companion apps.
     *
     * @example
     * ha.notify("Motion detected!", { title: "Security", target: "notify.mobile_app_my_phone" });
     *
     * @example
     * // With extra platform-specific data (e.g. image on Android/iOS):
     * ha.notify("Someone at the door", {
     *   title: "Doorbell",
     *   data: { image: "/local/snapshot.jpg", channel: "Doorbell" }
     * });
     */
    notify(message: string, options?: {
        /** Notification title shown in the push notification header. */
        title?: string;
        /**
         * Target notify service (e.g. `'notify.mobile_app_my_phone'` or just `'mobile_app_my_phone'`).
         * Defaults to `'notify.notify'` which broadcasts to all configured notifiers.
         */
        target?: string;
        /**
         * If true, sends the notification to Home Assistant's internal persistent notification system.
         * These appear in the web browser's sidebar.
         * When active, the 'target' option is ignored.
         */
        persistent?: boolean;
        /**
         * Platform-specific extra data passed under the `data` key of the notify service call.
         * Examples: `{ image: '/local/cam.jpg' }`, `{ channel: 'Alarm' }`, `{ tag: 'motion' }`.
         */
        data?: Record<string, any>;
    }): void;

    /**
     * Updates the state and/or attributes of an existing Home Assistant entity.
     * If the entity was registered via `ha.register`, it will use the native integration.
     * Otherwise, it falls back to the legacy HTTP API.
     * @param entityId The entity ID to update (e.g., 'sensor.my_sensor').
     * @param state The new state value.
     * @param attributes Optional attributes to set.
     */
    update(entityId: EntityID, state: string | number | boolean | null, attributes?: Record<string, any>): void;
    /**
     * Updates only the attributes of an existing Home Assistant entity, preserving its current state.
     * @param entityId The entity ID to update (e.g., 'sensor.my_sensor').
     * @param attributes Attributes to set or update.
     */
    update(entityId: EntityID, attributes: Record<string, any>): void;

    /**
     * @deprecated Use ha.update() instead.
     * Updates the state and/or attributes of an existing Home Assistant entity.
     * @param entityId The entity ID to update.
     * @param state The new state value.
     * @param attributes Optional attributes to set.
     */
    updateState(entityId: EntityID, state: string | number | boolean | null, attributes?: Record<string, any>): void;

    /**
     * Registers a native Home Assistant entity via MQTT Discovery.
     * Creates a persistent entity in Home Assistant's registry.
     * Calling `ha.register()` again with the same `entityId` updates the configuration.
     *
     * @example
     * ha.register('sensor.outside_temp', {
     *   name: 'Outside Temperature',
     *   icon: 'mdi:thermometer',
     *   unit: '°C',
     *   device_class: 'temperature',
     *   state_class: 'measurement',
     *   initial_state: 0,
     * });
     *
     * @example
     * ha.register('switch.sprinkler', { name: 'Sprinkler', icon: 'mdi:sprinkler' });
     * ha.register('select.mode', { name: 'Mode', options: ['auto', 'manual', 'off'] });
     *
     * @param entityId The desired entity ID (e.g., `'sensor.my_value'`). The domain determines the entity type.
     * @param config Configuration for the entity.
     */
    register(entityId: string, config?: {
        /** Display name shown in HA (defaults to a prettified version of the entity ID). */
        name?: string;
        /** Alias for `name`. */
        friendly_name?: string;
        /** MDI icon (e.g. `'mdi:thermometer'`). Can be changed at runtime via `ha.update()`. */
        icon?: string;
        /** Unit of measurement (e.g. `'°C'`, `'%'`, `'W'`). Alias: `unit`. */
        unit_of_measurement?: string;
        /** Alias for `unit_of_measurement`. */
        unit?: string;
        /** HA device class (e.g. `'temperature'`, `'humidity'`, `'power'`). */
        device_class?: string;
        /** HA state class for long-term statistics: `'measurement'`, `'total'`, `'total_increasing'`. */
        state_class?: 'measurement' | 'total' | 'total_increasing';
        /**
         * Places the entity in HA's diagnostic or config category.
         * - `'diagnostic'`: shown in a separate "Diagnostic" section (e.g. signal strength, uptime)
         * - `'config'`: shown in a separate "Configuration" section (e.g. thresholds, modes)
         */
        entity_category?: 'diagnostic' | 'config';
        /** Minimum value for `number` entities. */
        min?: number;
        /** Maximum value for `number` entities. */
        max?: number;
        /** Step size for `number` entities. */
        step?: number;
        /** Display mode for `number` entities: `'auto'`, `'box'`, or `'slider'`. */
        mode?: 'auto' | 'box' | 'slider';
        /** Number of decimal places HA should display for sensor values (e.g. `2` → `23.45 °C`). */
        suggested_display_precision?: number;
        /** Whether the entity is enabled in HA by default. Set to `false` to create it disabled. */
        enabled_by_default?: boolean;
        /** Seconds after the last state update before HA marks the entity as `unavailable`. */
        expire_after?: number;
        /** Initial state value set when the entity is first created. */
        initial_state?: string | number | boolean;
        /** Initial attributes (merged with the state on first publish). */
        attributes?: Record<string, any>;
        /** Direct area ID to assign this entity to (e.g. `'living_room'`). Takes precedence over `area`. */
        area_id?: string;
        /** Area name to assign this entity to (e.g. `'Living Room'`). Resolved to area ID automatically. */
        area?: string;
        /** Alias for `area`. */
        suggested_area?: string;
        /** Label names or IDs to assign to this entity (e.g. `['System', 'Critical']`). */
        labels?: string[];
        /**
         * Options list for `select` entities.
         * @example ['auto', 'manual', 'off']
         */
        options?: string[];
        /**
         * Groups this entity under a device in Home Assistant.
         * - `true`: use the script's name and slug as the device (e.g. all entities from `my_script.js` → device "My Script")
         * - `object`: provide a custom device configuration
         *
         * **Note:** When a device block is present, HA generates the entity_id as
         * `{device_name_slug}_{entity_name_slug}`, ignoring `object_id`.
         * Omit `device` (default) to ensure the entity_id matches exactly what you pass to `ha.register()`.
         *
         * @example
         * // Group all entities from this script under one device card:
         * ha.register('sensor.outside_temp', { name: 'Outside Temperature', device: true });
         *
         * @example
         * // Custom device metadata:
         * ha.register('sensor.outside_temp', {
         *   name: 'Outside Temperature',
         *   device: { name: 'Weather Station', identifiers: ['my_weather_station'], model: 'v2' }
         * });
         */
        device?: true | {
            /** Device identifiers (defaults to `['jsa_script_<scriptSlug>']`). */
            identifiers?: string[];
            /** Device display name (defaults to the script's display name). */
            name?: string;
            /** Device manufacturer string (defaults to `'JS Automations'`). */
            manufacturer?: string;
            /** Device model string (defaults to `'Script'`). */
            model?: string;
        };
        /** Allow any additional HA discovery config fields. */
        [key: string]: any;
    }): void;

    /** A live cache of all Home Assistant entity states. */
    readonly states: HAEntities;
    /** Gets the current state object for a given entity ID. */
    getState<K extends EntityID>(entityId: K): K extends keyof HAEntities ? HAEntities[K] : HAState | undefined;
    /** Gets a specific attribute value for an entity. */
    getAttr<K extends EntityID>(entityId: K, attribute: AttributeKey<K>): any;
    /** Gets the state value of an entity, converting 'on'/'off' to boolean and numbers to number. */
    getStateValue(entityId: EntityID): string | number | boolean | undefined;
    /** Gets the members of a group entity. */
    getGroupMembers(entityId: EntityID): EntityID[];

    /**
     * Reads a value from the script's header (e.g., `@name`, `@icon`).
     * @param key The header key (e.g., 'name', 'icon').
     * @param defaultValue A fallback value if the header is not found.
     */
    getHeader(key: string, defaultValue?: any): any;

    /**
     * Selects one or more entities based on a pattern for bulk actions.
     * @param pattern An entity ID, a wildcard pattern (e.g., 'light.*'), an array of entity IDs, or a RegExp.
     */
    select<P extends string>(pattern: P | EntityID[] | RegExp): EntitySelector & SelectorServices<P>;

    /**
     * Registers a callback to be executed when an entity's state changes.
     * @param pattern An entity ID, a wildcard pattern (e.g., 'light.*'), an array of entity IDs, or a RegExp.
     * @param callback The function to call when the state changes.
     */
    on(pattern: EntityID | EntityID[] | RegExp | string, callback: (event: StateChangeData) => void): void;
    /**
     * Registers a callback to be executed when an entity's state changes, with an optional filter.
     * @param pattern An entity ID, a wildcard pattern (e.g., 'light.*'), an array of entity IDs, or a RegExp.
     * @param filter A filter string ('ne', 'eq', 'gt', 'ge', 'lt', 'le') or a specific value to compare against.
     * @param callback The function to call when the state changes and the filter condition is met.
     */
    on(pattern: EntityID | EntityID[] | RegExp | string, filter: ChangeFilter | string | number, callback: (event: StateChangeData) => void): void;
    /**
     * Registers a callback to be executed when an entity's state changes, with a filter and an optional threshold.
     * @param pattern An entity ID, a wildcard pattern (e.g., 'light.*'), an array of entity IDs, or a RegExp.
     * @param filter A filter string ('ne', 'eq', 'gt', 'ge', 'lt', 'le').
     * @param threshold A numeric or string threshold to compare the new state against.
     * @param callback The function to call when the state changes and the filter condition is met.
     */
    on(pattern: EntityID | EntityID[] | RegExp | string, filter: ChangeFilter, threshold: string | number, callback: (event: StateChangeData) => void): void;

    /**
     * Waits for a specific event or state change.
     * Returns a Promise that resolves when the condition is met.
     * @param pattern An entity ID, a wildcard pattern (e.g., 'light.*'), an array of entity IDs, or a RegExp.
     * @param options Optional: { timeout?: number }
     */
    waitFor(pattern: EntityID | EntityID[] | RegExp | string, options?: { timeout?: number }): Promise<StateChangeData>;
    /**
     * Waits for a specific event or state change with a filter.
     * @param pattern An entity ID, a wildcard pattern (e.g., 'light.*'), an array of entity IDs, or a RegExp.
     * @param filter A filter string ('ne', 'eq', 'gt', 'ge', 'lt', 'le') or a specific value to compare against.
     * @param options Optional: { timeout?: number }
     */
    waitFor(pattern: EntityID | EntityID[] | RegExp | string, filter: ChangeFilter | string | number, options?: { timeout?: number }): Promise<StateChangeData>;
    /**
     * Waits for a specific event or state change with a filter and threshold.
     * @param pattern An entity ID, a wildcard pattern (e.g., 'light.*'), an array of entity IDs, or a RegExp.
     * @param filter A filter string ('ne', 'eq', 'gt', 'ge', 'lt', 'le').
     * @param threshold A numeric or string threshold to compare the new state against.
     * @param options Optional: { timeout?: number }
     */
    waitFor(pattern: EntityID | EntityID[] | RegExp | string, filter: ChangeFilter, threshold: string | number, options?: { timeout?: number }): Promise<StateChangeData>;

    /**
     * Waits until a specific condition function returns true.
     * This is useful for complex state checks involving multiple entities.
     * @param condition A function that returns true when the desired state is met.
     * @param options Optional: { timeout?: number, pollInterval?: number }
     */
    waitUntil(condition: () => boolean, options?: { timeout?: number, pollInterval?: number }): Promise<void>;

    /**
     * Provides access to the global persistent store.
     */
    store: {
        /**
         * A direct reference to the current values in the store.
         * Accessing properties directly on `ha.store.val` will not trigger change listeners or persistence.
         * Use `ha.store.get` and `ha.store.set` for reactive and persistent operations.
         */
        readonly val: GlobalStoreSchema;

        /**
         * Sets a value in the Global Store.
         * @param key The key to store the value under.
         * @param value The value to store.
         * @param isSecret If true, the value will be masked in the UI.
         */
        set<K extends keyof GlobalStoreSchema>(key: K, value: GlobalStoreSchema[K], isSecret?: boolean): void;
        set<T = any>(key: string & { _?: never }, value: T, isSecret?: boolean): void;

        /**
         * Retrieves a value from the Global Store.
         * @param key The key of the value to retrieve.
         * @returns The stored value, or `undefined` if not found.
         */
        get<K extends keyof GlobalStoreSchema>(key: K): GlobalStoreSchema[K];
        get<T = any>(key: string & { _?: never }): T | undefined;

        /**
         * Deletes a value from the Global Store.
         * @param key The key of the value to delete.
         */
        delete(key: StoreKey): void;

        /**
         * Registers a callback to be executed when a specific store key's value changes.
         * @param key The store key to listen for changes on.
         * @param callback The function to call when the value changes.
         */
        on<K extends keyof GlobalStoreSchema>(key: K, callback: (newValue: GlobalStoreSchema[K] | undefined, oldValue: GlobalStoreSchema[K] | undefined) => void): void;
        on<T = any>(key: string & { _?: never }, callback: (newValue: T | undefined, oldValue: T | undefined) => void): void;
    };

    /**
     * Creates a persistent ref wrapper for a primitive value stored in `ha.store`.
     * Access and modify the value via `.value` — changes are automatically saved.
     * @example
     * const counter = ha.persistent('counter', 0);
     * counter.value++;
     * const enabled = ha.persistent('enabled', false);
     * enabled.value = true;
     */
    persistent<T extends string | number | boolean>(key: string, defaultValue: T): { value: T };

    /**
     * Creates a deep proxy for an object stored in `ha.store`,
     * automatically saving changes back to the store when properties are modified.
     * Ideal for managing complex configuration objects persistently.
     * @param key The store key where the object is saved.
     * @param defaultValue An optional default value if the key is not found in the store.
     * @returns A Proxy object that automatically persists changes.
     */
    persistent<K extends keyof GlobalStoreSchema>(key: K, defaultValue?: GlobalStoreSchema[K]): GlobalStoreSchema[K];
    persistent<T extends object = Record<string, any>>(key: string, defaultValue?: T): T;

    /**
     * Filesystem API — available when the `filesystem_enabled` setting is on.
     * Uses virtual paths: `internal://`, `shared://`, `media://`.
     * Requires `@permission fs:read` and/or `@permission fs:write` in the script header
     * when capability enforcement is active.
     */
    readonly fs?: HaFs;
}

/** Virtual path roots: internal://, shared://, media:// */
type VirtualPath = `internal://${string}` | `shared://${string}` | `media://${string}`;

/** File/directory metadata returned by ha.fs.stat() */
interface FsStat {
    size: number;
    modified: Date;
    isDirectory: boolean;
}

/**
 * Filesystem API injected as `ha.fs`.
 * Available only when the `filesystem_enabled` addon setting is enabled.
 */
interface HaFs {
    /**
     * Reads a file. Returns a UTF-8 string by default; pass `'binary'` for a Buffer.
     * @requires @permission fs:read
     */
    read(virtualPath: VirtualPath, encoding?: 'utf8'): Promise<string>;
    read(virtualPath: VirtualPath, encoding: 'binary'): Promise<Buffer>;

    /**
     * Writes (or overwrites) a file. Creates parent directories if needed.
     * @requires @permission fs:write
     */
    write(virtualPath: VirtualPath, data: string | Buffer): Promise<void>;

    /**
     * Appends data to a file. Creates the file and parent directories if needed.
     * @requires @permission fs:write
     */
    append(virtualPath: VirtualPath, data: string | Buffer): Promise<void>;

    /**
     * Returns `true` if the path exists (file or directory).
     * @requires @permission fs:read
     */
    exists(virtualPath: VirtualPath): Promise<boolean>;

    /**
     * Lists entries in a directory. Directory names are suffixed with `/`.
     * @requires @permission fs:read
     */
    list(virtualPath: VirtualPath): Promise<string[]>;

    /**
     * Returns file/directory metadata.
     * @requires @permission fs:read
     */
    stat(virtualPath: VirtualPath): Promise<FsStat>;

    /**
     * Moves or renames a file. Both paths must be valid virtual paths.
     * @requires @permission fs:write
     */
    move(srcVirtual: VirtualPath, destVirtual: VirtualPath): Promise<void>;

    /**
     * Deletes a file or directory (recursively for directories).
     * @requires @permission fs:write
     */
    delete(virtualPath: VirtualPath): Promise<void>;

    /**
     * Watches a file or directory for changes.
     * @param callback Called with `(event, filename)` on each change.
     * @returns Unsubscribe function — call it to stop watching.
     * @requires @permission fs:read
     */
    watch(virtualPath: VirtualPath, callback: (event: string, filename: string | null) => void): () => void;

    /**
     * Log rotation helper. Trims the file when it exceeds `maxSize`,
     * keeping up to `keep` numbered backup files.
     * @example
     * await ha.fs.rotate('internal://app.log', { maxSize: '5MB', keep: 3 });
     * // Produces: app.log, app.1.log, app.2.log, app.3.log
     * @requires @permission fs:write
     */
    rotate(virtualPath: VirtualPath, options?: { maxSize?: string | number; keep?: number }): Promise<void>;
}

/**
 * Represents a selection of Home Assistant entities for bulk operations.
 */
declare class EntitySelector {
    readonly list: HAState[];
    readonly count: number;

    constructor(entities: HAState[], ha: HA);

    /** Filters the current selection using a callback function. */
    where(callback: (entity: HAState) => boolean): EntitySelector;
    /** Executes a function for each entity in the selection. */
    each(callback: (entity: HAState) => void): EntitySelector;
    /** Calls a service for all entities in the selection. */
    call(service: string, data?: Record<string, any>): Promise<this>;
    /** Sets a delay in milliseconds between each entity call in a batch action. */
    throttle(ms: number): this;
    /** Waits for the specified amount of time. Useful for chaining actions. */
    wait(ms: number): Promise<this>;
    /** Expands groups to their members. */
    expand(): EntitySelector;
    /** Returns the raw array of state objects. */
    toArray(): HAState[];
}

/**
 * Defines the possible filter types for `ha.on` and `ha.waitFor`.
 */
type ChangeFilter = 'ne' | 'eq' | 'gt' | 'ge' | 'lt' | 'le';